### ISSUE TITLE
Remove un-used components from 2019 code

### ISSUE THREAD

**Issue by lindsayvallen** [first95/FRC2019#13]
Specifically, remove all components, subsystems, and commands for the following: collector and climber. The robot drivebase and elevator will be similar enough this year to last year to keep and modify them.

**Comment by lindsayvallen** [comment]
When done, make sure the code compiles. Then go through and check again that everything that should be removed has been, and everything that should stay hasn't been removed.

**Comment by 0NotApplicable0** [comment]
Removed all components, subsystems, and commands for the collector and climber. Also removed related controls and solenoid definitions in OI and Constants. Code builds on most recent WPI VSCode.

Do we also want to remove the random assignment for switch and scale as it is no longer going to be used?

**Comment by jwalthour** [comment]
THanks, looks good!  Yeah, I think we can take those out.

**Comment by 0NotApplicable0** [comment]
All the sections for switch and scale operations were removed. NOTE: Automove selection was based of the switch and scale colors so it we try to run automoves getSelectedCommand only reutrns new Nothing(). Will need to fix how we select automoves.

**Comment by jwalthour** [comment]
Ah good point - thanks Nick!
