### ISSUE TITLE
Add stub sub-system for (hatch) ground loader

### ISSUE THREAD

**Issue by lindsayvallen** [first95/FRC2019#15]
The ground loader will have two moving parts -- a set of rollers to pull the hatch in, and a wrist to rotate the hatch to a vertical orientation. The rollers will be operated by a motor with encoder, and the wrist either also a motor/encoder or possibly a set of pneumatics.

**Comment by 0NotApplicable0** [comment]
Added the basics for a hatch ground loader. The wrist action for the ground loader uses last years DPAD setup. Pushed on the feature/hatch_ground_loader branch

**Comment by 0NotApplicable0** [comment]
Code has not been deployed to robot so the chain driver numbers and solenoid numbers in code are probably not right and most likely will not work as intended.
