### ISSUE TITLE
Add live stream from camera via co-processor to Dashboard

### ISSUE THREAD

**Issue by lindsayvallen** [first95/FRC2019#18]

**Comment by jwalthour** [comment]
For SmartDashboard, this must be done every time the dashboard is cleared.  These are the steps:

1. Enter editable mode (View->Editable or ctrl-E)
2. Click view->add->MJPEG stream viewer. A red rectangle will appear reading "NO CONNECTION".
3. Right-click the red rectangle and click "properties".
![image](https://user-images.githubusercontent.com/6525608/52902415-7364d700-31de-11e9-82ae-49643c001bef.png)
4. Double-click the cell to the right of "MJPG Server URL".  Paste in the address `http://frc95vision.local:1181/stream.mjpg`.
![image](https://user-images.githubusercontent.com/6525608/52902428-9abba400-31de-11e9-9b4f-08cacedd7bfb.png)
5. Press enter and close the properties box.  You will get a very tiny view.
![image](https://user-images.githubusercontent.com/6525608/52902433-ad35dd80-31de-11e9-94f2-1394a54b3bd7.png)
6. Grab and drag the corners of the image to resize
![image](https://user-images.githubusercontent.com/6525608/52902440-bf178080-31de-11e9-89fd-0a5a7e8a532b.png)
7. Press ctrl-E again or click View->Editable to exit editing view

**Comment by jwalthour** [comment]
Now the pi is at the static IP address `10.0.95.60`, so the MJPG stream is now `http://10.0.95.60:1181/stream.mjpg`
