### ISSUE TITLE
Create pseudo-code algorithm for automated scoring based on vision info

### ISSUE THREAD

**Issue by lindsayvallen** [first95/FRC2019#19]
Plan is for vision co-processor to provide a list of target pairs with the following info:
- Range (to the center point between target pair)
- Bearing from reference point on robot to target pair (can give input on that reference point in issue #11 )

Write pseudo-code for algo that takes these inputs and:
a) Determines which target pair should approach
b) Drive toward it
c) Repeat until reach some desired location relative to target pair
d) Scores game part

**Comment by jwalthour** [comment]
Basic idea is to drive forward quickly if far away, but slower if we're not facing the target squarely.

![2019-1-26 basic equations](https://user-images.githubusercontent.com/6525608/51790418-06bc6680-2163-11e9-9012-8d198e9b7b11.jpg)
