### ISSUE TITLE
Take more pretty pictures of vision targets

### ISSUE THREAD

**Issue by lindsayvallen** [first95/FRC2019#21]
Take more useful photos to understand and test vision processing. Set up hatch target at appropriate height from the floor and add floor vision target at appropriate location below it. Take various photos of the set of targets (one hatch consisting of two strips and one floor consisting of one strip) with the camera at different combinations of: range (distance between camera and targets), bearing angle (angle of approach), and incidence angle (angle at which camera would run into target). See forthcoming Slack posting from @jwalthour illustrating what the terms bearing angle and incidence angle mean.

**Comment by NHDinosaur** [comment]
Not sure if done. Not gonna take more.
