### ISSUE TITLE
Update vision co-processor to account for camera offset

### ISSUE THREAD

**Issue by lindsayvallen** [first95/FRC2019#27]
Expect that camera will be somewhat horizontally offset from the center of the robot. The vision processing code will need to be updated to account for that offset.

**Comment by jwalthour** [comment]
First draft in 4eef8f5809884a59d24355d28f0fd077a5e0f359; need to test.

**Comment by jwalthour** [comment]
Finished in e27301a9fe63076a39cc6202416dcaa7322576c9
