### ISSUE TITLE
Automove Selection

### ISSUE THREAD

**Issue by 0NotApplicable0** [first95/FRC2019#28]
How do we want to select automoves this year? A single mutable chooser that has simple and compound moves dynamically updated based off robot position?

Possibly three mutable choosers so drivers can create moves on the go?

**Comment by jwalthour** [comment]
I just realized - with the [sandstorm](https://www.youtube.com/watch?v=gFsdPrBLHO0) we may not even need any auto move selection.

I think we should see how bad it is to drive the robot with the camera in first-person view, and if we need full automation, we'll want to come back to this issue.

**Comment by lindsayvallen** [comment]
I concur. For cleanliness of code, I suggest we remove all of the auto move selection for now, and add it back only if we determine it's needed.

**Comment by 0NotApplicable0** [comment]
Removed everything to do with auto move selection.

**Comment by NHDinosaur** [comment]
This issue is just clogging space so I'm closing for 2020 repo.
