### ISSUE TITLE
Human Driver Control Requests

### ISSUE THREAD

**Issue by 0NotApplicable0** [first95/FRC2019#43]
Lara has requested that the hatch panel to release when the left bumper (5) is pressed
     - Remove holding down to keep hatch in loader

**Comment by 0NotApplicable0** [comment]
I just saw a spreadsheet was made for controls:

https://docs.google.com/spreadsheets/d/17dYB1nawOt3gQoEPz9w_w4j_zVCD92162E-oP9PuYYQ/edit#gid=1451237021

**Comment by jwalthour** [comment]
Looks like we accidentally made a duplicate in #48
