### ISSUE TITLE
Make more sophisticated command/control for Hab level 3 climber

### ISSUE THREAD

**Issue by lindsayvallen** [first95/FRC2019#47]
Currently just has throttle control for driver and button-hold for skid deployment.

**Comment by jwalthour** [comment]
Skid deployment is now a toggle.  We may want to:
- Make the climber have a hold position capability, much like the elevator and the cargo loader
- Add an interlock that lifts the hatch ground loader wrist whenever the skids are deployed

**Comment by jwalthour** [comment]
This is on hold until (and if) we remove our hab level 2 climber and install something like our old level 3 climber.

**Comment by lindsayvallen** [comment]
Removing this from advanced automation milestone since we're not doing any climber stuff right now.

**Comment by NHDinosaur** [comment]
Never added hab level 3 climber back on.
