### ISSUE TITLE
Add mechanical homing switch to hatch ground loader

### ISSUE THREAD

**Issue by jwalthour** [first95/FRC2019#58]
Draft support is in feature/hgl_collector_rehoming.  Switch is not yet present on robot.

**Comment by lindsayvallen** [comment]
From discussion with Andy, the homing switch will probably be magnetic and be in the wrist's up position. @jwalthour Does the code you stubbed out work for this set-up?

**Comment by jwalthour** [comment]
Yup, should work!  I just merged develop in and fixed one apparent bug.  It
expects the same "active low" configuration as the elevator home switch pin.

**Comment by NHDinosaur** [comment]
Not sure if done. Not doing now.
