### ISSUE TITLE
Elevator rehome button doesn't work

### ISSUE THREAD

**Issue by jwalthour** [first95/FRC2019#65]
Drivers report that the last time they tried to use this button, the elevator spooled down out-of-control.

Have not reproduced in a controlled environment.

**Comment by lindsayvallen** [comment]
Attempt at fix in commit 0be07eb where use of re-homing button is handled in the main elevator command so that isn't working independently of the button. Need to test it.

**Comment by lindsayvallen** [comment]
Tested and seems to work so pushed into develop.
